# Generated by Django 5.0 on 2023-12-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='arendhouse',
        ),
        migrations.RemoveField(
            model_name='users',
            name='izbran_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='newarend',
        ),
    ]
