# Generated by Django 5.0 on 2023-12-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_users_arendhouse_remove_users_izbran_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='id_arend',
        ),
        migrations.RemoveField(
            model_name='house',
            name='timees',
        ),
        migrations.AddField(
            model_name='house',
            name='times',
            field=models.BooleanField(default=False, verbose_name='вид времени аренды'),
        ),
        migrations.AlterField(
            model_name='house',
            name='adres',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='house',
            name='child',
            field=models.BooleanField(default=False, verbose_name='можно ли с детьми'),
        ),
        migrations.AlterField(
            model_name='house',
            name='opisanie',
            field=models.CharField(max_length=300, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='house',
            name='pet',
            field=models.BooleanField(default=False, verbose_name='можно ли с животными'),
        ),
        migrations.AlterField(
            model_name='house',
            name='type_user',
            field=models.BooleanField(default=False, verbose_name='кто сдаёт(арендует)'),
        ),
    ]
