# Generated by Django 5.0 on 2023-12-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_house_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='child',
        ),
        migrations.RemoveField(
            model_name='house',
            name='data_obnav',
        ),
        migrations.RemoveField(
            model_name='house',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='house',
            name='times',
        ),
        migrations.RemoveField(
            model_name='house',
            name='type_user',
        ),
        migrations.AlterField(
            model_name='house',
            name='photo',
            field=models.FileField(max_length=15, upload_to='', verbose_name='фото'),
        ),
    ]
