# Generated by Django 5.0 on 2023-12-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_house_child_remove_house_data_obnav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='photo',
            field=models.FileField(upload_to='', verbose_name='фото'),
        ),
    ]
