# Generated by Django 5.0 on 2023-12-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_house_photo_alter_house_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='id_User',
        ),
    ]
