# Generated by Django 5.0 on 2023-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_house_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='photo',
            field=models.ImageField(upload_to=None, verbose_name='фото'),
        ),
    ]
