# Generated by Django 5.0 on 2023-12-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_house_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='id_User',
            field=models.CharField(default='0', max_length=200, verbose_name='id пользователя'),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='фото'),
        ),
    ]
