# Generated by Django 5.0 on 2023-12-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_house_id_user_alter_house_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='id_password',
            field=models.CharField(default='0', max_length=200, verbose_name='id пользователя'),
        ),
    ]
