# Generated by Django 5.0 on 2023-12-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_house_id_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='фото'),
        ),
    ]
