# Generated by Django 5.0 on 2023-12-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_house_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='idd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField(verbose_name='индекс')),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='photo',
            field=models.ImageField(upload_to='static/images', verbose_name='фото'),
        ),
    ]
