# Generated by Django 5.0 on 2023-12-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_idd_alter_house_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idd',
            old_name='idd',
            new_name='iddd',
        ),
    ]
