# Generated by Django 5.0 on 2023-12-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_idd_idd_iddd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='id_password',
        ),
        migrations.AlterField(
            model_name='house',
            name='id_User',
            field=models.CharField(max_length=200, verbose_name='id пользователя'),
        ),
    ]
