# Generated by Django 5.0 on 2023-12-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_house_id_password_alter_house_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='child',
            field=models.CharField(default='нет', max_length=200, verbose_name='можно ли с детьми'),
        ),
        migrations.AddField(
            model_name='house',
            name='pet',
            field=models.CharField(default='нет', max_length=200, verbose_name='можно ли с животными'),
        ),
        migrations.AddField(
            model_name='house',
            name='times',
            field=models.CharField(default='Месяц', max_length=200, verbose_name='вид времени аренды'),
        ),
    ]
