# Generated by Django 5.0 on 2023-12-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0020_delete_house_delete_idd_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_User', models.CharField(max_length=200, verbose_name='id пользователя')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('photo', models.ImageField(upload_to='static/images', verbose_name='фото')),
                ('times', models.CharField(default='Месяц', max_length=200, verbose_name='вид времени аренды')),
                ('type_house', models.CharField(max_length=200, verbose_name='тип сдованмого жилья')),
                ('child', models.CharField(default='нет', max_length=200, verbose_name='можно ли с детьми')),
                ('pet', models.CharField(default='нет', max_length=200, verbose_name='можно ли с животными')),
                ('max_People', models.IntegerField(verbose_name='максимум человек')),
                ('razmer', models.IntegerField(verbose_name='площадь')),
                ('kol_komnat', models.IntegerField(verbose_name='количество комнат')),
                ('adres', models.CharField(max_length=200, verbose_name='Адрес')),
                ('opisanie', models.CharField(max_length=300, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='idd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddd', models.IntegerField(verbose_name='индекс')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('Email', models.EmailField(max_length=254, verbose_name='Эмэил')),
                ('password', models.CharField(max_length=200, verbose_name='пароль')),
                ('telephone', models.IntegerField(verbose_name='телефон')),
            ],
        ),
    ]
