# Generated by Django 4.1.7 on 2023-12-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='photo',
        ),
        migrations.AddField(
            model_name='house',
            name='photo1',
            field=models.ImageField(default='static/0.jpg', upload_to='static/images', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='house',
            name='photo2',
            field=models.ImageField(default='static/0.jpg', upload_to='static/images', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='house',
            name='photo3',
            field=models.ImageField(default='static/0.jpg', upload_to='static/images', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='house',
            name='photo4',
            field=models.ImageField(default='static/0.jpg', upload_to='static/images', verbose_name='фото'),
        ),
    ]
