# Generated by Django 4.1.7 on 2023-12-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_house_photo1_alter_house_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='telephone',
            field=models.CharField(default=1, max_length=10, verbose_name='номер телефона'),
            preserve_default=False,
        ),
    ]
