# Generated by Django 4.1.7 on 2023-12-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_house_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='номер телефона'),
        ),
    ]
