# Generated by Django 4.1.7 on 2023-12-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_house_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Название обьявления'),
            preserve_default=False,
        ),
    ]
