# Generated by Django 4.1.7 on 2023-12-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='idd',
            name='search',
            field=models.CharField(default=1, max_length=50, verbose_name='поиск'),
            preserve_default=False,
        ),
    ]
