# Generated by Django 4.1.7 on 2023-12-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_idd_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='opisanie',
            field=models.CharField(default=None, max_length=200, verbose_name='описание'),
        ),
    ]
