# Generated by Django 4.1.7 on 2023-12-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_house_opisanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='opisanie',
            field=models.CharField(blank=True, max_length=200, verbose_name='описание'),
        ),
    ]
